### ISSUE TITLE
Passwords are leaked to thir parties

### ISSUE THREAD

**Issue by jomo** [SirCmpwn/evilpass#11]
I know this is kind of the whole point, but any password you enter will be sent to Twitter, Facebook, GitHub, Reddit, Hacker News, and Google. (And thus the NSA? :¬)

I've been doing [a very similar thing](https://github.com/RedstonerServer/redstoner.com/blob/b057cb591344828ceead2d8b156832d332a9991d/app/controllers/users_controller.rb#L103-L105) for years and only decided to keep it because the password is sent to just one third party which authorizes the account anyways.

I don't know how to fix this, but you should keep it in mind!

**Comment by SirCmpwn** [comment]
*shrug* This isn't meant for serious use.

**Comment by SirCmpwn** [comment]
:+1: for `is_idiot = true` though :D

**Comment by jomo** [comment]
fun fact: it actually sends out [these](https://i.imgur.com/y3w5L7Y.png) "special" registration mails to "idiots" :)
