### ISSUE TITLE
Stop enforcing hard to remember passwords

### ISSUE THREAD

**Issue by Benoth** [SirCmpwn/evilpass#2]
While I agree on minimal password length, forcing lower/upper/numbers/specials is no good practice at all. I use a very easy to remember password (in fact, a pass phrase), 30+ characters long whom does not respond this requirements. It's much more secure than a 8 characters long password meeting this requirements.

Calculating a minimal complexity could be a nice answer to this problem.

Related :
- http://softwareengineering.stackexchange.com/questions/113911/what-is-a-reasonable-and-secure-password-requirement-for-user-registration
- https://xkcd.com/936/

**Comment by Jonjoe** [comment]
Although I appreciate the sentiment with which this issue was created. I am left wondering whether the author understands satire. Does he not know this is obviously a pretty awesome joke? No-one in their right right mind (hold on, this the internet ...) would use this for anything, hack or production ...

**Comment by qgustavor** [comment]
From the readme seems the objective of this rule is supporting the user of password managers: use random and hard to remember passwords for websites and hard to guess but easy to remember passwords for password managers.

But even if it's the objective then why not making it explicit in the error message?

**Comment by JacksonKearl** [comment]
#7 fixes this.

**Comment by SirCmpwn** [comment]
Merged a PR that mentions entropy harder in the README and mentions the NIST guidelines. #7 is also under discussion. I did mention in the readme that the checks were contrived, it just makes for a funnier GIF to hook you with :wink:
