### ISSUE TITLE
Adding different systems.

### ISSUE THREAD

**Issue by AtheistOfFail** [SirCmpwn/evilpass#5]
If you want quick implementations of additional external services, rip the code right out of my fork of shard that is rewritten in python -> https://github.com/AtheistOfFail/shard/tree/master/secondary_implementations/python

The modules correspond to one single external service and just take in a uname/password and return a true/false.

**Comment by SirCmpwn** [comment]
Adding new systems is a perpetual task, I'd rather not explicitly have an issue open for it. Send a pull request if you'd like. Also, we use Python 3 here.
